### ISSUE TITLE
Stateless functions React 0.14 compat

### ISSUE THREAD

**Issue by Sinewyk** [jordangarcia/nuclear-js-react-addons#11]
This is probably not going to be pretty with https://github.com/jordangarcia/nuclear-js-react-addons/blob/4854ba6a95e0745348e43365759847df869d488b/nuclearComponent.js#L109 ...

Find a better way or let it go because there's a pretty simple solution to avoid problems ...

**Comment by jordangarcia** [comment]
This should be fixed in `0.3.0` with the `connect` function :)
