### ISSUE TITLE
Remove unnecessary files from NPM published package

### ISSUE THREAD

**Issue by raulmatei** [jordangarcia/nuclear-js-react-addons#18]
We've tried to use NuclearJS with React Native, but we've got into this issue:
![image](https://cloud.githubusercontent.com/assets/1718341/15472701/2d2cf4b2-2105-11e6-8910-aa7c2af64fc6.png)

The best way would be to add a `"files"` property into `package.json`:

``` js
{
  "files": ["build", "dist"]
}
```

This way you'll end up with a clean package. I feel that there's no need to have the sources published on NPM or am I wrong?

I can submit a PR if you can help me with the files list that you want to get into the published package.

Raul.

**Comment by jordangarcia** [comment]
feel free to PR and I will publish a new version

**Comment by raulmatei** [comment]
#19 is up, feel free to add more files into that list, if needed.

Thanks,
Raul.

**Comment by jordangarcia** [comment]
@raulmatei I published `0.4.1` with these changes, let me know if that solves your problems

**Comment by raulmatei** [comment]
Thanks @jordangarcia, it's fine on our side. Hope no one imported something directly from `src` directory which is excluded.
