### ISSUE TITLE
No AMD/UMD?

### ISSUE THREAD

**Issue by hipertracker** [jordangarcia/nuclear-js-react-addons#3]
That package looks to be CommonJS only so it's tough to use in AMD without help of Browserify/Webpack. Any plans for adding AMD/UMD version?

**Comment by Sinewyk** [comment]
Wow, completely slipped my mind. I'll see about providing a umd build.

**Comment by Sinewyk** [comment]
@jordangarcia close this when you release npm with built umd files ?
