### ISSUE TITLE
Dynamic getters not supported on annotations

### ISSUE THREAD

**Issue by kungfoolabs** [jordangarcia/nuclear-js-react-addons#9]
I am a bit new to nuclearjs, but it seems like Dynamic getters are not supported with the nuclearComponent annotation. 

For example, I am only interested in getting data from the store filtered by one of the `Component` props.

Eg. `getter.function(this.props.property)`

I think the solution is for `nuclearComponent` to allow functions in the dataBindings and for `forEach` function to pass either the component or the props to the function?

**Comment by Sinewyk** [comment]
You mean exactly like the nuclearMixin ... Blame my laziness.
Yeah, i'll probably do that later, you will be able to either pass an object or a function that returns an object.

**Comment by Sinewyk** [comment]
Could you test https://github.com/jordangarcia/nuclear-js-react-addons/tree/nuclear_component_dynamic_bindings ?

I mean in your code if that's what you want.

That's a backward incompatible change that reflects the nuclearMixin api, now the bindings always takes a function that returns the binding object.

**Comment by Sinewyk** [comment]
Did you test the branch ?

**Comment by Sinewyk** [comment]
Supported now on tag 0.2.0
